### ISSUE TITLE
Leaving Org

### ISSUE THREAD

**Issue by kerrtravers** [smelt-modding/smelt-modding.github.io#14]
I'm sorry to announce that I've had to leave the organization today, Mostly because I'm too busy with other private projects and my profile was getting too messy.

Could I be added as a contributor though? I would still love to continue working on this project when I can.

**Comment by Kenny2github** [comment]
I'll assume you've already left - I've invited you as a collaborator.

**Comment by kerrtravers** [comment]
Thank you
