### ISSUE TITLE
Indentation isn’t obvious

### ISSUE THREAD

**Issue by Kenny2github** [smelt-modding/smelt-modding.github.io#5]
#### Expected behavior
The indentation in the content of the installation section should be clear
#### Actual behavior
![db181766-f30e-4606-8dcb-6d0048f4374b](https://user-images.githubusercontent.com/28599280/31342508-95602672-ad3f-11e7-83e5-60a7721a6dea.jpeg)
The indentation is not visible. It’s slightly part of the content. Could this be made more obvious somehow? The sentence structure is supposed to be “there will be: two new folders; five new files”

**Comment by VutonDesign** [comment]
@Kenny2github Would a change of colour do? (A darker blue)

**Comment by kerrtravers** [comment]
@Kenny2github How's this?
![capture](https://user-images.githubusercontent.com/26391179/31343862-ceba76fc-ad08-11e7-8116-25b78d5826ef.JPG)
